const BUILDER_URL = window.location.origin
export const Filter_System = [
  {
    id: 'tbl158T8gIujpOOW1',
    name: 'Patient',
  },
  {
    id: 'tblQP89YJ4Y85djQt',
    name: 'Blood',
  },
  {
    id: 'tbl1xvmSChYmjwrTd',
    name: 'Urine',
  },
  {
    id: 'tblurjtKjBiJkTTOj',
    name: 'Other',
  },
  {
    id: 'tblUL3odoExuoKdH4',
    name: 'Calculators',
  },
]

export const Filter_Conditions = [
  {
    id: '1',
    name: 'and',
  },
  {
    id: '2',
    name: 'or',
  },
]

export const BASE_ID = [
  {
    id: 'appJ6LHBEjhaorG0k',
    name: 'Care Bundles',
  },
  {
    id: 'appOYFnQSnNcWioWs',
    name: 'LOINC',
  },
]

export const BLOCK_TYPES = {
  Structure: {
    Start: 'recPiOaYskQi3aGmr',
    End: 'recbBVLxQdZp16mtL',
    Choose: 'recW8SmmHSOUjo44e',
    Filter: 'recUTngsdR4I39G9W',
    Branch: 'rec8SnoKDGhEKUleU',
  },
  Action: {
    Elicit: 'recEalcj7ZzsWOtJl',
    Record: 'rec6GEaWgdlSAWnwq',
    Order: 'rec4aB5HyLP8PB7QR',
    Use: 'rec2c61MmfqLZOcAN',
    Schedule: 'reccjEwjEV27fKxss',
    Note: 'recCi3YAhvfzB3JCm',
    Custom: 'recs5i6f9bg4tyBUo',
    Prescribe: 'recSBk4FQlq6EENoY',
    Apply: 'recUBF7rqWRernF22',
    Link: 'recJba4cy2yGI2AWB',
    Differential: 'reck1dRIJa0IPP5WM',
  },
  Trigger: {
    Await: 'recEl8T6qvmuP1d96',
    NewPatient: 'recLD1nhMpKoK6cIa',
    RepeatTimer: 'recE5hnIc9FTbvdiG',
    NewAction: 'recRFZTjOvd9oymlZ',
  },
  Connect: {
    Contact: 'rec37uQebtcTnLvC3',
    Educate: 'recnYUekYuPoZKE0T',
    Remind: 'recR2roTOG9NuKAK7',
  },
}

export const START_BLOCK_TYPE = 'receULDV9Y9o12Gwa'

export const Right_Card = [
  {
    id: 'recfncYn4G187n9wh',
    name: 'Repeat timer',
    lefticon: `${BUILDER_URL}/assets/time_elapsed_blue.svg`,
    desc: 'Trigger care process at a set recurring period.',
    templateTitle: 'Define periods: ',
    template: '${period}',
    begin: 'Every ',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recrqj6Bnnt1xVh4n',
    name: 'New patient',
    lefticon: `${BUILDER_URL}/assets/new_patient_info_blue.svg`,
    desc: 'Trigger care process when a new patient is created.',
    templateTitle: '',
    template: 'When a new patient is created',
    begin: '',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recC1egF31qqdfZvo',
    name: 'New action',
    lefticon: `${BUILDER_URL}/assets/new_action_blue.svg`,
    desc: 'Trigger care process when a new action is performed.',
    template: 'When ${condition} is met',
    templateTitle: '',
    begin: '',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: false,
  },
  {
    id: 'recgrh1HqyGdnF6P4',
    name: 'Await result',
    lefticon: `${BUILDER_URL}/assets/new_data_blue.svg`,
    desc: 'Trigger care process when a new result is available.',
    templateTitle: 'Select one or more tests:',
    template: 'When ${condition} is met',
    begin: '',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: false,
  },
  {
    id: 'recFlff7nv4x5GeHb',
    name: 'Elicit',
    lefticon: `${BUILDER_URL}/assets/elicit_blue.svg`,
    desc: 'Elicit a set of clinical findings from a patient.',
    templateTitle: 'Select one or more findings:',
    template: '${findings}',
    begin: 'Elicit the following findings: ',
    isMulti: true,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recYDulWwW95t2jzG',
    name: 'Prescribe',
    lefticon: `${BUILDER_URL}/assets/prescribe_blue.svg`,
    desc: 'Prescribe one or more medications.',
    templateTitle: 'Select one or more dosages:',
    template: '${dosages}',
    begin: 'Write the following prescriptions: ',
    isMulti: true,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recWyLivc49yUG4I8',
    name: 'Order',
    lefticon: `${BUILDER_URL}/assets/order_blue.svg`,
    desc: 'Order a test for a patient.',
    templateTitle: 'Select one or more tests:',
    template: '${tests}',
    begin: 'Order the following tests: ',
    isMulti: true,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'rec1AbkYCywOlj1tk',
    name: 'Record',
    lefticon: `${BUILDER_URL}/assets/record_blue.svg`,
    desc: 'Record one or more diagnoses.',
    templateTitle: 'Select one or more diseases:',
    template: '${diseases}',
    begin: 'Record the following diagnoses: ',
    isMulti: true,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recf0K1X1cUHzzzLI',
    name: 'Apply',
    lefticon: `${BUILDER_URL}/assets/apply_blue.svg`,
    desc: 'Apply a guideline recommendation.',
    templateTitle: 'Select a keypoint:',
    template: '${keypoints}',
    begin: 'Apply the following guidelines: ',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recL9clggSCSPVbWq',
    name: 'Schedule',
    lefticon: `${BUILDER_URL}/assets/schedule_blue.svg`,
    desc: 'Schedule a follow-up visit.',
    templateTitle: 'Select a specialty:',
    template: '${visits}',
    begin: 'Schedule the following visits: ',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'reczByjxdzlstvaIL',
    name: 'Link',
    lefticon: `${BUILDER_URL}/assets/link_blue.svg`,
    desc: 'Link to another care bundle.',
    templateTitle: 'Select a pathway:',
    template: '${bundle}',
    begin: 'Link to this care bundle: ',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recMyU2ROZ09YVvA3',
    name: 'Use',
    lefticon: `${BUILDER_URL}/assets/use_blue.svg`,
    desc: 'Use a clinical calculator.',
    templateTitle: 'Select a calculator:',
    template: '${calculator}',
    begin: 'Use this calculator: ',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recYN0nLeXThBf4O5',
    name: 'Custom',
    lefticon: `${BUILDER_URL}/assets/custom_blue.svg`,
    desc: 'Write a block with custom text.',
    templateTitle: 'Custom text:',
    template: '',
    begin: '',
    isMulti: true,
    hasTextInput: true,
    hasSelectInput: true,
  },
  {
    id: 'recCrrDwthcB1wY61',
    name: 'Note',
    desc: 'Enter a block with custom text.',
    lefticon: `${BUILDER_URL}/assets/note_blue.svg`,
    templateTitle: '',
    template: '',
    begin: 'Text input will be placed hereasdf: ',
    isMulti: false,
    hasTextInput: true,
    hasSelectInput: false,
  },
  {
    id: 'recMEeq7a9kvdhlJp',
    name: 'Differential',
    lefticon: `${BUILDER_URL}/assets/use_blue.svg`,
    desc: 'Generate a differential diagnosis.',
    templateTitle: 'Select a presentation: ',
    template: '${presentation}',
    begin: 'Generate a differential diagnosis for: ',
    isMulti: false,
    hasSelectInput: true,
    hasTextInput: false,
  },
  {
    id: 'receULDV9Y9o12Gwa',
    name: 'Start',
    lefticon: `${BUILDER_URL}/assets/start_blue.svg`,
    desc: 'Begin care process.',
    templateTitle: '',
    template: 'Begin care process',
    begin: '',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: false,
  },
  {
    id: 'recBSHQXsamP6Re51',
    name: 'Filter',
    lefticon: `${BUILDER_URL}/assets/filter_blue.svg`,
    desc: 'Continue only if a specific condition is met.',
    templateTitle: '',
    template: 'When ${condition} is met',
    begin: 'If ',
    isMulti: false,
    hasTextInput: false,
    hasSelectInput: true,
  },
  {
    id: 'recFzs4p5SJ72HA8M',
    name: 'Branch',
    lefticon: `${BUILDER_URL}/assets/branch_blue.svg`,
    desc: 'Continue only if a specific condition is met. ',
    templateTitle: '',
    template: 'If ${expression}',
    begin: '',
    isMulti: false,
    hasSelectInput: true,
    hasTextInput: true,
  },
  {
    id: 'recebF0NuiiWrO7GS',
    name: 'Choose',
    lefticon: `${BUILDER_URL}/assets/branch_blue.svg`,
    desc: 'Branch on a specific condition.',
    templateTitle: '',
    template: 'Branch on a specific condition.',
    begin: '',
    isMulti: false,
    hasSelectInput: false,
    hasTextInput: false,
  },
  {
    id: 'reclGPhiwyIhGMuO6',
    name: 'End',
    lefticon: `${BUILDER_URL}/assets/end_blue.svg`,
    desc: 'End care process.',
    templateTitle: '',
    template: 'End of care process',
    begin: '',
    isMulti: false,
    hasSelectInput: false,
    hasTextInput: false,
  },
  {
    id: 'recUql0CX6UqxM2Je',
    name: 'Contact',
    lefticon: `${BUILDER_URL}/assets/contact_blue.svg`,
    desc: 'Contact a patient by e-mail or by phone.',
    templateTitle: '',
    template: 'Contact by: ',
    begin: '',
    isMulti: false,
    hasSelectInput: false,
    hasTextInput: false,
  },
  {
    id: 'recK49IvPELGK8b4g',
    name: 'Educate',
    lefticon: `${BUILDER_URL}/assets/education_blue.svg`,
    desc: 'Send an educational document to a patient.',
    templateTitle: '',
    template: 'Send the following handout: ',
    begin: '',
    isMulti: false,
    hasSelectInput: true,
    hasTextInput: false,
  },
  {
    id: 'recW2OFCkSdMoBxPT',
    name: 'Remind',
    lefticon: `${BUILDER_URL}/assets/reminder_blue.svg`,
    desc: 'Send a reminder to a patient.',
    templateTitle: '',
    template: 'Send a reminder by:  ',
    begin: '',
    isMulti: false,
    hasSelectInput: false,
    hasTextInput: false,
  },
]
